language: node_js
node_js:
- 10.12.0
sudo: required
dist: trusty
services:
  - mongodb
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^(hot)?fix.*$/"
  - "/^v[0-9].*$/"

git:
  depth: false

cache:
  bundler: true
  directories:
  - node_modules

jobs:
  include:
    - stage: test
      name: "Unit test"
      script:
        - npm run lint
        - NODE_ENV=testing-travis jest --config ./jest-cover.json --coverage --bail --forceExit --runInBand
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    
    - stage: release
      name: "Release"
      if: branch == master && !fork
      node_js: 'node'
      script:
        - echo "Releasing"

notifications:
  email:
    recipients:
    - trungdt@absoft.vn

env:
  matrix:
  - NODE_ENV=test
